server:
  port: 1010

app:
  name: Microservice Application



eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
    healthcheck:
      enabled: true
